#!/usr/bin/env python3
"""
extract-graph.py — turn a captured debugging session into a cases.js SKELETON.

    scripts/extract-graph.py session.jsonl [--id myhunt] > cases.draft.js

Input is JSON-lines. Each line is an object; the extractor looks for assistant
turns and pulls two kinds of "beats", in order:

  * reasoning  — a thinking/analysis block  -> becomes a step (title + narr)
  * action     — a tool call / command      -> becomes that step's code entry

It supports the common shape produced by agent transcripts:

    {"type":"assistant","message":{"content":[
        {"type":"thinking","thinking":"..."},
        {"type":"tool_use","name":"Bash","input":{"command":"...","description":"..."}}
    ]}}

...and a generic fallback: a line with a "thinking"/"reasoning"/"text" field is a
reasoning beat; a line with "command"/"action"/"tool" is an action beat.

What you get is a STARTER: one step per reasoning beat, edges as a straight
chain, and kind / lane / move / chapter left as TODO. The tool does the
transcription; you supply the judgement — which beats were dead ends (kind
"deadend", lane 1), where the pivot and backtrack are, and the lesson. See
docs/authoring.md and docs/moves.md.
"""
import sys, json, argparse, re

def first_sentence(s, n=64):
    s = " ".join(s.split())
    m = re.split(r"(?<=[.!?])\s", s, maxsplit=1)
    t = m[0] if m else s
    return (t[:n] + "…") if len(t) > n else t

def beats_from_line(obj):
    """Yield ('reason', text) / ('action', label) beats from one JSONL record."""
    if obj.get("type") == "assistant" and isinstance(obj.get("message"), dict):
        for c in obj["message"].get("content", []) or []:
            t = c.get("type")
            if t in ("thinking", "reasoning") and c.get(t):
                yield ("reason", c[t])
            elif t == "text" and c.get("text"):
                yield ("reason", c["text"])
            elif t == "tool_use":
                inp = c.get("input") or {}
                label = inp.get("description") or inp.get("command") or c.get("name") or "action"
                yield ("action", f'{c.get("name","tool")}: {label}')
        return
    # generic fallback
    for k in ("thinking", "reasoning", "text"):
        if obj.get(k):
            yield ("reason", obj[k]); break
    for k in ("command", "action", "tool"):
        if obj.get(k):
            yield ("action", str(obj[k])); break

def esc(s):
    return s.replace("\\", "\\\\").replace("`", "\\`")

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("jsonl")
    ap.add_argument("--id", default="hunt")
    ap.add_argument("--max-steps", type=int, default=40)
    a = ap.parse_args()

    reasons, pending_actions = [], []
    with open(a.jsonl, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
            except json.JSONDecodeError:
                continue
            for kind, payload in beats_from_line(obj):
                if kind == "reason":
                    reasons.append({"narr": payload, "actions": pending_actions})
                    pending_actions = []
                else:
                    pending_actions.append(payload)
    if pending_actions and reasons:
        reasons[-1]["actions"].extend(pending_actions)

    reasons = [r for r in reasons if len(r["narr"].split()) >= 6][: a.max_steps]
    if not reasons:
        sys.exit("no reasoning beats found — is this the right file/format?")

    out = []
    out.append("/* SKELETON generated by extract-graph.py — TAG THE TODOs. */")
    out.append('window.APP_TITLE = "Bug Hunt";')
    out.append(f"const STEPS_{a.id} = [")
    for r in reasons:
        title = first_sentence(r["narr"])
        narr = esc(" ".join(r["narr"].split()))
        out.append("  {chapter:\"TODO\", kind:\"win\"/*TODO evidence|deadend|pivot|win|root|retro*/, "
                   "move:\"TODO\"/*docs/moves.md*/, lane:0/*1=detour*/,")
        out.append(f"   title:{json.dumps(title)},")
        out.append(f"   narr:`{narr}`}},")
    out.append("];")
    out.append(f"const CODE_{a.id} = [")
    for r in reasons:
        acts = r["actions"][:4] or ["(no action captured for this step)"]
        lines = ",".join("P(" + json.dumps(x) + ")" for x in acts)
        out.append(f"  {{lang:\"action\", cap:\"TODO\", body:[{lines}]}},")
    out.append("];")
    out.append(f"const EDGES_{a.id} = [")
    out.append("  " + ", ".join("{f:%d,t:%d,type:\"seq\"}" % (i, i + 1)
                                for i in range(len(reasons) - 1)))
    out.append("]; // TODO: mark branch / backtrack / shortcut edges")
    out.append("window.CASES = window.CASES || {};")
    out.append(f'window.CASES["{a.id}"] = {{name:"TODO", sub:"TODO", '
               f"steps:STEPS_{a.id}, code:CODE_{a.id}, edges:EDGES_{a.id}, "
               f"audio:/*AUDIO_{a.id}_START*/null/*AUDIO_{a.id}_END*/}};")
    print("\n".join(out))

if __name__ == "__main__":
    main()
